#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e

if (( $# != 1 )); then
	echo "Illegal number of parameters"
	echo "usage: services [create|start|stop]"
	exit 1
fi

stoppingContainers () {
	echo "Stopping containers"
	docker-compose --log-level ERROR -f docker-compose/$1.yml -p fiware down -v --remove-orphans
}

displayServices () {
	echo ""
	docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter name=fiware-*
	echo ""
}

command="$1"
case "${command}" in
	"help")
		echo "usage: services [create|start|stop]"
		;;
	"orion")
		stoppingContainers orion
		echo -e "Starting two containers \033[1;34mOrion\033[0m and a \033[1;30mMongoDB\033[0m database."
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo ""
		docker-compose --log-level ERROR -f docker-compose/orion.yml -p fiware up -d --remove-orphans
		displayServices
		;;
	"scorpio")
		stoppingContainers scorpio
		echo -e "Starting four containers \033[1;34mScorpio\033[0m, \033[1;30mKafka\033[0m, \033[1;30mZookeeper\033[0m and a \033[1;30mPostgres\033[0m database."
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo ""
		docker-compose --log-level ERROR -f docker-compose/scorpio.yml -p fiware up -d --remove-orphans
		displayServices
		;;
	"stop")
		stoppingContainers scorpio
		stoppingContainers orion
		;;
	"create")
		echo "Obtaining Mongo DB image"
		docker pull mongo:3.6
		echo "Obtaining Latest Orion Image"
		docker pull fiware/orion-ld
		;;
	*)
		echo "Command not Found."
		echo "usage: services [create|orion|scorpio|stop]"
		exit 127;
		;;
esac