version: "3.5"
services:
  zookeeper:
    hostname: zookeeper
    image: zookeeper
    container_name: zookeeper
    networks:
      - default
    ports:
      - "2181:2181"


  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - default
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  postgres-db:
    hostname: postgres
    image: mdillon/postgis
    container_name: db-postgres
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb

  scorpio:
    hostname: scorpio
    image: scorpiobroker/scorpio:scorpio-aaio
    container_name: fiware-scorpio
    networks:
      - default
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - postgres-db